---
- name: Ensure userli plugin is latest
  ansible.builtin.git:
    repo: "https://github.com/systemli/roundcube-userli-plugin"
    dest: "{{ roundcube_working_dir }}/current/plugins/userli"
    version: main
  become_user: "{{ roundcube_user }}"
  become: true

- name: Ensure userli plugin config is latest
  ansible.builtin.template:
    src: plugins/userli/config.inc.php.j2
    dest: "{{ roundcube_working_dir }}/current/plugins/userli/config.inc.php"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0640"
