---
- name: Retrieve latest userli plugin version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/systemli/roundcube-userli-plugin/releases/latest"
    headers:
      Accept: "application/vnd.github+json"
      X-GitHub-Api-Version: "2022-11-28"
    body_format: json
  register: latest_release

- name: Ensure userli plugin is latest
  ansible.builtin.git:
    repo: "https://github.com/systemli/roundcube-userli-plugin"
    dest: "{{ roundcube_working_dir }}/current/plugins/userli"
    version: "{{ latest_release.json.tag_name }}"
  become_user: "{{ roundcube_user }}"
  become: true
  check_mode: no

- name: Ensure userli plugin config is latest
  ansible.builtin.template:
    src: plugins/userli/config.inc.php.j2
    dest: "{{ roundcube_working_dir }}/current/plugins/userli/config.inc.php"
    owner: "{{ roundcube_user }}"
    group: "{{ roundcube_group }}"
    mode: "0640"
